# Site settings
title: HABIR, hashing baseline for image retrieval
tag_text: Solo
description: Various hashing methods for image retrieval and serves as the baselines.

# Build settings
markdown: kramdown

exclude: ["README.md"]
